//
//  dummyStories.swift
//  HackerNews
//
//  Created by Ben Gabay on 2/28/23.
//

import Foundation


let story = Story(by: "Ben",
                  id: 0,
                  score: 100,
                  time: 1677723071,
                  title: "Bens cool article",
                  type: .story,
                  url: "http://ben.com/beniscool",
                  descendants: 0,
                  kids: nil,
                  text: "some Text")
let story1 = Story(by: "Bens_Cousin101",
                   id: 0,
                   score: 90,
                   time: 1677733422,
                   title: "Programming solved, I think",
                   type: .story,
                   url: "http://ben.com/beniscool",
                   descendants: 0,
                   kids: nil,
                   text: "some Text")
let story2 = Story(by: "EcoManxxx",
                   id: 0,
                   score: 112,
                   time: 1677750676,
                   title: "Natural Forest pops up in the sahara",
                   type: .story,
                   url: "http://nature.com",
                   descendants: 0,
                   kids: nil,
                   text: "I'm going to get a job")
let story3 = Story(by: "Xx_d[-_-]b_xX",
                   id: 0,
                   score: 69,
                   time: 1677766826,
                   title: "Traveling by Futurama tubes are the future",
                   type: .story,
                   url: "http://yahoo.com",
                   descendants: 0,
                   kids: nil,
                   text: "some Text")
let story4 = Story(by: "Joe Shmoe",
                   id: 0,
                   score: 231,
                   time: 1677609396,
                   title: "The internet has just been invented! Again!",
                   type: .story,
                   url: "http://aUsefulWebsite.com",
                   descendants: 0,
                   kids: nil,
                   text: "The machines are taking over")
let story5 = Story(by: "ARandomUser1113",
                   id: 0,
                   score: 34,
                   time: 1677677621,
                   title: "Show HN - House powered by Hamsters",
                   type: .story,
                   url: "http://bestbuyHamsters.com",
                   descendants: 0,
                   kids: nil,
                   text: "some Text")
let story6 = Story(by: "IlovedogsLOL",
                   id: 0,
                   score: 99,
                   time: 1677603974,
                   title: "Birds are not real, for real",
                   type: .story,
                   url: "http://birdsarentreal.com",
                   descendants: 0,
                   kids: nil,
                   text: "I repeat, birds ARE NOT REAL")
let story7 = Story(by: "TomFromMyspace",
                   id: 0,
                   score: 100,
                   time: 1677617962,
                   title: "I love skateboarding and you should too",
                   type: .story,
                   url: "http://myspace.com",
                   descendants: 0,
                   kids: nil,
                   text: "some Text")
let story8 = Story(by: "MustachedOilBaron",
                   id: 0,
                   score: 100,
                   time: 1677766173,
                   title: "Oil is best",
                   type: .story,
                   url: "http://oilIsBest.com",
                   descendants: 0,
                   kids: nil,
                   text: "some Text")
let story9 = Story(by: "JohnnyStorm",
                   id: 0,
                   score: 100,
                   time: 1677616198,
                   title: "Superhero denied a loan today",
                   type: .story,
                   url: "http://AnExampleHere.com",
                   descendants: 0,
                   kids: nil,
                   text: "some Text")
let story10 = Story(by: "I_wear_shorts",
                   id: 0,
                   score: 100,
                   time: 1677616198,
                   title: "Shorts said to lengthen life",
                   type: .story,
                   url: "http://AnExampleHere2.com",
                   descendants: 0,
                   kids: nil,
                   text: "some Text")
let story11 = Story(by: "bing_me",
                   id: 0,
                   score: 100,
                   time: 1677616198,
                   title: "SWE is most sexy job according to people",
                   type: .story,
                   url: "http://softwareengineering.com",
                   descendants: 0,
                   kids: nil,
                   text: "some Text")
let story12 = Story(by: "l33t_h4x",
                   id: 0,
                   score: 100,
                   time: 1677616198,
                   title: "Solve MITM attacks using the scripts",
                   type: .story,
                   url: "http://AnExampleHere.com",
                   descendants: 0,
                   kids: nil,
                   text: "some Text")
let story13 = Story(by: "UserUsingHN",
                   id: 0,
                   score: 100,
                   time: 1677616198,
                   title: "A super title",
                   type: .story,
                   url: "http://AnExampleHere.com",
                   descendants: 0,
                   kids: nil,
                   text: "some Text")
let story14 = Story(by: "ComputerMan1001",
                   id: 0,
                   score: 100,
                   time: 1677616198,
                   title: "Silicon chip may be replaced soon",
                   type: .story,
                   url: "http://AnExampleHere.com",
                   descendants: 0,
                   kids: nil,
                   text: "some Text")
let story15 = Story(by: "HNReader",
                   id: 0,
                   score: 100,
                   time: 1677616198,
                   title: "Startups work < 10% of the time",
                   type: .story,
                   url: "http://AnExampleHere.com",
                   descendants: 0,
                   kids: nil,
                   text: "some Text")
let story16 = Story(by: "BankMan111",
                   id: 0,
                   score: 100,
                   time: 1677616198,
                   title: "Banks are Banks",
                   type: .story,
                   url: "http://AnExampleHere.com",
                   descendants: 0,
                   kids: nil,
                   text: "some Text")
let dummyStories = [story, story1, story2, story3, story4, story5, story6, story7, story8, story9, story10, story11, story12, story13, story14, story15]

let comment1 = Comment(by: "Example User",
                       id: 35016553,
                       kids: nil,
                       parent: 35015624,
                       text: "Hello this is just an example",
                       time: 1677887295,
                       type: .comment,
                       deleted: false
                       )
let comment2 = Comment(by: "Example User",
                       id: 35016553,
                       kids: nil,
                       parent: 35015624,
                       text: "Hello this is just an example",
                       time: 1677887295,
                       type: .comment,
                       deleted: false
                       )
let comment3 = Comment(by: "Example User",
                       id: 35016553,
                       kids: nil,
                       parent: 35015624,
                       text: "Hello this is just an example",
                       time: 1677887295,
                       type: .comment,
                       deleted: false
                       )
let comment4 = Comment(by: "Example User",
                       id: 35016553,
                       kids: nil,
                       parent: 35015624,
                       text: "Hello this is just an example",
                       time: 1677887295,
                       type: .comment,
                       deleted: false
                       )
let comment5 = Comment(by: "Example User",
                       id: 35016553,
                       kids: nil,
                       parent: 35015624,
                       text: "Hello this is just an example",
                       time: 1677887295,
                       type: .comment,
                       deleted: false)
let comment6 = Comment(by: "Example User",
                       id: 35016553,
                       kids: nil,
                       parent: 35015624,
                       text: "Hello this is just an example",
                       time: 1677887295,
                       type: .comment,
                       deleted: false)
let dummyComments = [comment1, comment2, comment3, comment4, comment5, comment6]
